config/routes.rb
Rails.application.routes.draw do
  get 'potin/:id', to: 'dynamic_pages#potin', as: 'potin'
  get 'user/:id', to: 'dynamic_pages#user', as: 'user'
  get '/', to: 'static_pages#index', as: 'index'
  get '/connection', to: 'static_pages#connection', as: 'connection'
  get '/team', to: 'static_pages#team', as: 'team'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/welcome', to: 'static_pages#welcome', as: 'welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potin.rb
class Potin < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :potins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
  def potin
    @id_potin = params[:id]
  end

  def user
    @id_user = params[:id]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def connection
  end

  def welcome
  end

  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dynamic_pages/potin.html.erb
<% potin = Potin.find(@id_potin)
    @title = potin.title
    @content = potin.content
    @user = potin.user.first_name 
    @user_id = potin.user_id 
    @time = potin.created_at
    %>
<div class="container">
  <h1> Voila les détails du potin </h1>
  <blockquote class="blockquote">
    <h3 class="mb-0 font-weight-bold"> <%= @title %> </h3>
    <p class="text-justify"> <%= @content %> </p>
    <p>Par <%=link_to @user,user_path(@user_id)%></p>
    <p>Le <%=@time %></p>
  </blockquote>
</div>

app/views/dynamic_pages/user.html.erb
<% user = User.find(@id_user)

@first_name = user.first_name
@last_name = user.last_name
%>
<div class="container">
    <h1>Voici la page de profile de : </h1>
    <p>Prénom : <%= @first_name %> </p>
    <p>Nom de famille : <%= @last_name %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
   
    <nav class="navbar navbar-expand-lg navbar-light bg-light d-flex">
      <a class="navbar-brand" href="/">Gossips</a>
      <a class="navbar-brand" href="/connection">Connexion</a>
      <a class="navbar-brand" href="/contact">Contact</a>
      <a class="navbar-brand" href="/team">Team</a>
    </nav>
   
    <%= yield %>
  </body>
</html>

app/views/static_pages/connection.html.erb
<h1>Renseignez nous votre prénom :</h1>
<form action="/welcome" method="get">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="first_name">Prénom : </label>
    <input type="text" name="first_name">
    <input type="submit" name="Envoyer">
</form>

app/views/static_pages/contact.html.erb
<div class="card-deck">
    <div class="card text-center">
        <div class="card-body">
            <h1 class="card-title">Florian Even</h1>
            <p class="card-text">Son mail : ouibonjour@gmail.com</p>
        </div>
    </div>
    <div class="card text-center">
        <div class="card-body">
            <h1 class="card-title">Samir Kettani</h1>
            <p class="card-text">Son mail : sasuke-53@hotmail.fr</p>
        </div>
    </div>
</div>

app/views/static_pages/index.html.erb
<div class="card-deck text-center mb-3">
<% 
Potin.all.each do |potin|
    @first_name = potin.user.first_name
    @title = potin.title
    @content = potin.content 
    @id = potin.id
    %>
    <div class="card mb-4" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title"><%= @title %> </h5>
        <p class="card-text"> <%= @first_name %> </p>
    <%=link_to "Potin", potin_path(@id), class:"btn btn-primary" %>
    </div>
    </div>
<% 
end %>
</div>

app/views/static_pages/team.html.erb
<h1> BZH TEAM </h1>

<p> Nous nous sommes rencontré sous le beau soleil de bretagne, moi samir et mon sensei flo.
 Il avait une belle chevelure, blond. On aurait dit un prince charmant. Sous ce soleil de plomb de bretagne il me tendit un shushen.
Après 8 verres nous visitons les rues de Rennes. Et voilla comment je me suis réveillé au côté de flo qui est devenu aujourd'hui mon compagnon pour ce project </p>

app/views/static_pages/welcome.html.erb
<h1>Bonjour <%=params[:first_name]%></h1>